import Phaser from "phaser";
import { ASSETS } from "../config/assetPaths.js";
import { animationConfig } from "../config/animationConfig.js";
import { CREATURES } from "../data/creatures.js";
import { pixelArtGenerator } from "../systems/pixelArtGenerator.js";

/**
 * PreloadScene
 * Responsible for loading all game assets.
 * Displays a loading bar to the user.
 */
export class PreloadScene extends Phaser.Scene {
  constructor() {
    super({ key: "PreloadScene" });
  }

  preload() {

    // Create loading UI
    this.createLoadingUI();

    // 1. Generic Image Assets (Faces, Battlebacks, Parallaxes, Tilesets)
    const imageCats = [
      "BATTLEBACKS1",
      "BATTLEBACKS2",
      "PARALLAXES",
      "TILESETS",
      "SYSTEM",
    ];
    imageCats.forEach((cat) => {
      Object.values(ASSETS[cat]).forEach((asset) => {
        this.load.image(asset.KEY, asset.PATH);
      });
    });

    // 2. Spritesheets (Characters, Animations, Faces, Monster Fallbacks)
    const sheetCats = ["CHARACTERS", "ANIMATIONS", "FACES", "SPRITES"];
    sheetCats.forEach((cat) => {
      Object.entries(ASSETS[cat]).forEach(([name, asset]) => {
        if (asset.FRAME_CONFIG) {
          this.load.spritesheet(asset.KEY, asset.PATH, asset.FRAME_CONFIG);
        } else if (cat === "ANIMATIONS") {
          // configKey (e.g. "Fire1") is used only for animationConfig lookup, not as a texture key.
          // All textures are registered under asset.KEY (e.g. "anim_fire1").
          const configKey =
            name.charAt(0).toUpperCase() + name.slice(1).toLowerCase();
          const config = animationConfig[configKey];

          if (config) {
            this.load.spritesheet(asset.KEY, asset.PATH, {
              frameWidth: config.frameWidth,
              frameHeight: config.frameHeight,
            });
          } else if (asset.grid) {
            this.load.spritesheet(asset.KEY, asset.PATH, {
              frameWidth: 192,
              frameHeight: 192,
            });
          } else {
            this.load.image(asset.KEY, asset.PATH);
          }
        } else if (asset.grid) {
          this.load.spritesheet(asset.KEY, asset.PATH, {
            frameWidth: 192,
            frameHeight: 192,
          });
        } else {
          this.load.image(asset.KEY, asset.PATH);
        }
      });
    });

    // 3. Icons (Loaded individually as generated by splitIconSet.js)
    // 39 rows, 16 columns = 624 icons
    for (let r = 0; r < 39; r++) {
      for (let c = 0; c < 16; c++) {
        const rowStr = String(r).padStart(2, "0");
        const colStr = String(c).padStart(2, "0");
        const key = `icon_${rowStr}_${colStr}`;
        this.load.image(key, `/assets/icons/${key}.png`);
      }
    }

    // 4. Creature Sprites
    Object.values(ASSETS.CREATURES).forEach((asset) => {
      this.load.image(asset.KEY, asset.PATH);
    });

    // 5. Audio Assets
    const audioCats = ["BGM", "BGS", "ME", "SE"];
    audioCats.forEach((cat) => {
      Object.values(ASSETS.AUDIO[cat]).forEach((asset) => {
        this.load.audio(asset.KEY, asset.PATH);
      });
    });

    // Error handling
    this.load.on("loaderror", (file) => {
      console.warn(
        `PreloadScene: Failed to load asset: ${file.key} at ${file.src}`,
      );
    });

    // Load Start Scene Cutscene Backgrounds
    Object.values(ASSETS.CUTSCENE_IMAGES).forEach((asset) => {
      this.load.image(asset.KEY, asset.PATH);
    });
  }

  create() {

    // Initialize Audio Manager
    import("../systems/audioManager.js").then((module) => {
      module.audioManager.init(this.game);
      // Create placeholder textures at runtime so the game is playable without external files
      this.createPlaceholderTextures();

      // Transition to StartScene
      this.scene.start("StartScene");
    });
  }

  createLoadingUI() {
    const { width, height } = this.cameras.main;

    // Background for loading
    this.add.rectangle(0, 0, width, height, 0x011627).setOrigin(0);

    const rainbowColors = [
      0xff0000, 0xff9f1c, 0xf1c40f, 0x2ecc71, 0x3498db, 0x9b59b6,
    ];
    const rainbowGraphics = this.add.graphics();

    // Use the transparent image asset loaded in BootScene
    const nyanSprite = this.add
      .sprite(width / 2 - 200, height / 2, "nyan_cat_clean")
      .setOrigin(0.5);

    // Set size to be slightly larger than the rainbow (which is ~36px total)
    nyanSprite.setDisplaySize(90, 80); // Slightly bigger than rainbow height

    const loadingText = this.make
      .text({
        x: width / 2,
        y: height / 2 + 80,
        text: "가냥... (Loading Feloria...)",
        style: {
          font: "bold 20px Arial",
          fill: "#ffffff",
          stroke: "#000000",
          strokeThickness: 3,
        },
      })
      .setOrigin(0.5);

    this.load.on("progress", (value) => {
      const centerX = width / 2;
      const centerY = height / 2;
      const barWidth = 500;
      const x = centerX - barWidth / 2 + barWidth * value;

      nyanSprite.x = x;

      // Vertical wiggle
      nyanSprite.y = centerY + Math.sin(this.time.now / 120) * 8;

      // Draw Rainbow Trail
      rainbowGraphics.clear();
      const trailX = centerX - barWidth / 2;
      const currentProgressX = x - 20; // Behind the cat

      const rainbowHeight = 6; // Thinner rainbow

      for (let i = 0; i < 6; i++) {
        rainbowGraphics.fillStyle(rainbowColors[i], 1);
        const yOffset = (i - 3) * rainbowHeight;

        // Wavy trail
        const points = [];
        for (let tx = trailX; tx <= currentProgressX; tx += 12) {
          const ty =
            centerY + yOffset + Math.sin((this.time.now - tx) / 120) * 8;
          points.push({ x: tx, y: ty });
        }

        if (points.length > 1) {
          for (let p = 0; p < points.length - 1; p++) {
            rainbowGraphics.fillRect(
              points[p].x,
              points[p].y,
              13,
              rainbowHeight,
            );
          }
        }
      }
    });

    this.load.on("complete", () => {
      // Small delay for flair
      this.time.delayedCall(500, () => {
        nyanSprite.destroy();
        rainbowGraphics.destroy();
        loadingText.destroy();
      });
    });
  }

  createPlaceholderTextures() {
    pixelArtGenerator.createPlaceholders(this);
  }
}
