import Phaser from "phaser";
import { ASSETS } from "../config/assetPaths.js";
import { animationConfig } from "../config/animationConfig.js";
import { CREATURES } from "../data/creatures.js";
import { pixelArtGenerator } from "../systems/pixelArtGenerator.js";
import bgContinent from "../data/graphics/startscene/펠로리아 대륙.png";
import bgAncientCats from "../data/graphics/startscene/고대 고양이.png";
import bgTwistedForest from "../data/graphics/startscene/뒤틀린 숲.png";
import bgShadow from "../data/graphics/startscene/흑막.png";
import bgTitleScreen from "../data/graphics/startscene/Feloria_title_screen.png";

/**
 * PreloadScene
 * Responsible for loading all game assets.
 * Displays a loading bar to the user.
 */
export class PreloadScene extends Phaser.Scene {
  constructor() {
    super({ key: "PreloadScene" });
  }

  preload() {
    console.log("PreloadScene: Loading assets...");

    // Create loading UI
    this.createLoadingUI();

    // 1. Generic Image Assets (Faces, Battlebacks, Parallaxes, Tilesets)
    const imageCats = [
      "BATTLEBACKS1",
      "BATTLEBACKS2",
      "PARALLAXES",
      "TILESETS",
      "SYSTEM",
    ];
    imageCats.forEach((cat) => {
      Object.values(ASSETS[cat]).forEach((asset) => {
        this.load.image(asset.KEY, asset.PATH);
      });
    });

    // 2. Spritesheets (Characters, Animations, Faces, Monster Fallbacks)
    const sheetCats = ["CHARACTERS", "ANIMATIONS", "FACES", "SPRITES"];
    sheetCats.forEach((cat) => {
      Object.entries(ASSETS[cat]).forEach(([name, asset]) => {
        if (asset.FRAME_CONFIG) {
          this.load.spritesheet(asset.KEY, asset.PATH, asset.FRAME_CONFIG);
        } else if (cat === "ANIMATIONS") {
          // Use Case-Sensitive Name (e.g., FIRE1 -> Fire1)
          const configKey =
            name.charAt(0).toUpperCase() + name.slice(1).toLowerCase();
          const config = animationConfig[configKey];

          if (config) {
            this.load.spritesheet(configKey, asset.PATH, {
              frameWidth: config.frameWidth,
              frameHeight: config.frameHeight,
            });
            // Also load as .KEY for any systems that might use it
            this.load.spritesheet(asset.KEY, asset.PATH, {
              frameWidth: config.frameWidth,
              frameHeight: config.frameHeight,
            });
          } else if (asset.grid) {
            this.load.spritesheet(configKey, asset.PATH, {
              frameWidth: 192,
              frameHeight: 192,
            });
            this.load.spritesheet(asset.KEY, asset.PATH, {
              frameWidth: 192,
              frameHeight: 192,
            });
          } else {
            this.load.image(configKey, asset.PATH);
            this.load.image(asset.KEY, asset.PATH);
          }
        } else if (asset.grid) {
          this.load.spritesheet(asset.KEY, asset.PATH, {
            frameWidth: 192,
            frameHeight: 192,
          });
        } else {
          this.load.image(asset.KEY, asset.PATH);
        }
      });
    });

    // 3. Icons (Loaded individually as generated by splitIconSet.js)
    // 39 rows, 16 columns = 624 icons
    for (let r = 0; r < 39; r++) {
      for (let c = 0; c < 16; c++) {
        const rowStr = String(r).padStart(2, "0");
        const colStr = String(c).padStart(2, "0");
        const key = `icon_${rowStr}_${colStr}`;
        this.load.image(key, `/assets/icons/${key}.png`);
      }
    }

    // 4. Creature Sprites
    Object.entries(ASSETS.CREATURES).forEach(([id, asset]) => {
      this.load.image(id.toLowerCase(), asset.PATH);
      // Also load with .KEY for consistency in some systems
      this.load.image(asset.KEY, asset.PATH);
    });

    // 5. Audio Assets
    const audioCats = ["BGM", "BGS", "ME", "SE"];
    audioCats.forEach((cat) => {
      Object.values(ASSETS.AUDIO[cat]).forEach((asset) => {
        this.load.audio(asset.KEY, asset.PATH);
      });
    });

    // Error handling
    this.load.on("loaderror", (file) => {
      console.warn(
        `PreloadScene: Failed to load asset: ${file.key} at ${file.src}`,
      );
    });

    // Load Start Scene Cutscene Backgrounds (Legacy/Fallback)
    this.load.image("bg_continent", bgContinent);
    this.load.image("bg_ancient_cats", bgAncientCats);
    this.load.image("bg_twisted_forest", bgTwistedForest);
    this.load.image("bg_shadow", bgShadow);
    this.load.image("bg_title_screen", bgTitleScreen);
  }

  create() {
    console.log(
      "PreloadScene: Assets loaded, creating placeholder textures...",
    );

    // Initialize Audio Manager
    import("../systems/audioManager.js").then((module) => {
      module.audioManager.init(this.game);
      // Create placeholder textures at runtime so the game is playable without external files
      this.createPlaceholderTextures();

      // Transition to StartScene
      this.scene.start("StartScene");
    });
  }

  createLoadingUI() {
    const { width, height } = this.cameras.main;

    // Background for loading
    this.add.rectangle(0, 0, width, height, 0x011627).setOrigin(0);

    const rainbowColors = [
      0xff0000, 0xff9f1c, 0xf1c40f, 0x2ecc71, 0x3498db, 0x9b59b6,
    ];
    const rainbowGraphics = this.add.graphics();

    // Use the transparent image asset loaded in BootScene
    const nyanSprite = this.add
      .sprite(width / 2 - 200, height / 2, "nyan_cat_clean")
      .setOrigin(0.5);

    // Set size to be slightly larger than the rainbow (which is ~36px total)
    nyanSprite.setDisplaySize(90, 80); // Slightly bigger than rainbow height

    const loadingText = this.make
      .text({
        x: width / 2,
        y: height / 2 + 80,
        text: "가냥... (Loading Feloria...)",
        style: {
          font: "bold 20px Arial",
          fill: "#ffffff",
          stroke: "#000000",
          strokeThickness: 3,
        },
      })
      .setOrigin(0.5);

    this.load.on("progress", (value) => {
      const centerX = width / 2;
      const centerY = height / 2;
      const barWidth = 500;
      const x = centerX - barWidth / 2 + barWidth * value;

      nyanSprite.x = x;

      // Vertical wiggle
      nyanSprite.y = centerY + Math.sin(this.time.now / 120) * 8;

      // Draw Rainbow Trail
      rainbowGraphics.clear();
      const trailX = centerX - barWidth / 2;
      const currentProgressX = x - 20; // Behind the cat

      const rainbowHeight = 6; // Thinner rainbow

      for (let i = 0; i < 6; i++) {
        rainbowGraphics.fillStyle(rainbowColors[i], 1);
        const yOffset = (i - 3) * rainbowHeight;

        // Wavy trail
        const points = [];
        for (let tx = trailX; tx <= currentProgressX; tx += 12) {
          const ty =
            centerY + yOffset + Math.sin((this.time.now - tx) / 120) * 8;
          points.push({ x: tx, y: ty });
        }

        if (points.length > 1) {
          for (let p = 0; p < points.length - 1; p++) {
            rainbowGraphics.fillRect(
              points[p].x,
              points[p].y,
              13,
              rainbowHeight,
            );
          }
        }
      }
    });

    this.load.on("complete", () => {
      // Small delay for flair
      this.time.delayedCall(500, () => {
        nyanSprite.destroy();
        rainbowGraphics.destroy();
        loadingText.destroy();
      });
    });
  }

  /**
   * Generates simple placeholder textures for development using pixelArtGenerator.
   * This provides a massive visual upgrade over plain rectangles!
   */
  createPlaceholderTextures() {
    // ----------------------------------------------------------------
    // 1. TILESET (Empty, Grass, Dirt, Water, Wall, TallGrass, Tree)
    // ----------------------------------------------------------------
    const tEmpty = Array(16).fill("................");
    const tGrass = [
      "EEEEEEEEEEEEEEEE",
      "EEGEEEEEEEEEEEEE",
      "EEEEEEEGEEEEEEEE",
      "EEEEEEEEEEEEEEEE",
      "EEEEEEEEEEEEGEEE",
      "EGEEEEEEEEEEEEEE",
      "EEEEEEEEEEEEEEEE",
      "EEEEEEGEEEEEEEEE",
      "EEEEEEEEEEEEEEEE",
      "EEEEEEEEEEEGEEEE",
      "EEGEEEEEEEEEEEEE",
      "EEEEEEEEEEEEEEEE",
      "EEEEEEEGEEEEEEEE",
      "EEEEEEEEEEEEEEEE",
      "EEEEEEEEEEEEGEEE",
      "EEEEEEEEEEEEEEEE",
    ];
    const tDirt = [
      "vvvvvvvvvvvvvvvv",
      "vvWvvvvvvvvvvvvv",
      "vvvvvvvwvvvvvvvv",
      "vvvvvvvvvvvvWvvv",
      "vvvvwvvvvvvvvvvv",
      "vvvvvvvvvvWvvvvv",
      "vvvvvvvvwvvvvvvv",
      "vvWvvvvvvvvvvvvv",
      "vvvvvvvvvvvvvvvv",
      "vvvvvWvvvvvvvvwv",
      "vvvvvvvvvvvvvvvv",
      "vvwvvvvvvWvvvvvv",
      "vvvvvvvvvvvvvvvv",
      "vvWvvvvvvvvvvwvv",
      "vvvvvvvvvvvvvvvv",
      "vvvvvvvvwvvvvvvv",
    ];
    const tWater = [
      "bbbbbbbbbbbbbbbb",
      "bbbbbsbbbbbbbbbb",
      "bbbbbbbbbbbbbbbs",
      "bbbbbbbbbbbbbbbb",
      "bbsbbbbbbbbbbbbb",
      "bbbbbbbbbsbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbsbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbsbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbs",
      "bbsbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbsbbbbbb",
    ];
    const tWall = [
      "2222222222222222",
      "3333333133333331",
      "3333333133333331",
      "3333333133333331",
      "1111111111111111",
      "3331333333313333",
      "3331333333313333",
      "3331333333313333",
      "1111111111111111",
      "3333333133333331",
      "3333333133333331",
      "3333333133333331",
      "1111111111111111",
      "3331333333313333",
      "3331333333313333",
      "3331333333313333",
    ];
    const tTallGrass = [
      "EEEEEEEEEEEEEEEE",
      "EEEGGGEEEEEGGGEE",
      "EEGGgGGEEEEGGgGE",
      "EGgGGGEEEEEGGgGE",
      "GGGGGGGEEEGGGGGG",
      "GgGGgGGEEEGgGGgG",
      "GGGGGGGGEEGGGGGG",
      "EEGGGGGEEEEGGGGG",
      "EGGgGGEEEEEGGgGE",
      "GGGGGGGEEEGGGGGG",
      "GgGGgGGEEEGgGGgG",
      "GGGGGGGGEEGGGGGG",
      "EEEGGGEEEEEGGGEE",
      "EEGGGGGEEEEGGGGG",
      "EGGgGGEEEEEGGgGE",
      "EEEEEEEEEEEEEEEE",
    ];
    const tTree = [
      "......GGGG......",
      "....GGGGGGGG....",
      "...GGGGGGGGGG...",
      "..GGGGGGGGGGGG..",
      "..GGGGGGGGGGGG..",
      ".GGGGGGGGGGGGGG.",
      ".GGGGGGGGGGGGGG.",
      ".GGGGGGGGGGGGGG.",
      ".GGGGGGGGGGGGGG.",
      "..GGGGGGGGGGGG..",
      "...GGGGGGGGGG...",
      ".....wwwwww.....",
      ".....wWwwWw.....",
      ".....wwWwww.....",
      ".....wwwwww.....",
      "......wwww......",
    ];

    pixelArtGenerator.createTileset(
      this,
      "overworld-tiles",
      [tEmpty, tGrass, tDirt, tWater, tWall, tTallGrass, tTree],
      2,
    );

    // ----------------------------------------------------------------
    // 2. PLAYER SPRITE (Human Explorer: Down, Up, Left, Right)
    // ----------------------------------------------------------------
    const pDown = [
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "....HHffffHH....",
      "....Hff00ffH....",
      "....HffffffH....",
      ".....ffffff.....",
      "....bbbbbbbb....",
      "...bbbbbbbbbb...",
      "...bbbbbbbbbb...",
      "...bbbbbbbbbb...",
      "....KKKKKKKK....",
      "....KKKKKKKK....",
      "....KK....KK....",
      "....KK....KK....",
      "....00....00....",
      "....00....00....",
    ];
    const pUp = [
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "....HHHHHHHH....",
      "....HHHHHHHH....",
      "....HHHHHHHH....",
      ".....HHHHHH.....",
      "....bbbbbbbb....",
      "...bbbbbbbbbb...",
      "...bbbbbbbbbb...",
      "...bbbbbbbbbb...",
      "....KKKKKKKK....",
      "....KKKKKKKK....",
      "....KK....KK....",
      "....KK....KK....",
      "....00....00....",
      "....00....00....",
    ];
    const pLeft = [
      ".....HHHHH......",
      "....HHHHHHH.....",
      "....HffffHH.....",
      "....Hff0fHH.....",
      "....HffffHH.....",
      ".....fffff......",
      "....bbbbbbb.....",
      "...bbbbbbbbb....",
      "...bbbbbbbbb....",
      "...bbbbbbbbb....",
      "....KKKKKKK.....",
      "....KKKKKKK.....",
      "....KK...KK.....",
      "....KK...KK.....",
      "....00...00.....",
      "....00...00.....",
    ];
    const pRight = [
      "......HHHHH.....",
      ".....HHHHHHH....",
      ".....HHffffH....",
      ".....HHf0ffH....",
      ".....HHffffH....",
      "......fffff.....",
      ".....bbbbbbb....",
      "....bbbbbbbbb...",
      "....bbbbbbbbb...",
      "....bbbbbbbbb...",
      ".....KKKKKKK....",
      ".....KKKKKKK....",
      ".....KK...KK....",
      ".....KK...KK....",
      ".....00...00....",
      ".....00...00....",
    ];
    pixelArtGenerator.createSpritesheet(
      this,
      "player",
      [pDown, pUp, pLeft, pRight],
      16,
      16,
      2,
    );

    // ----------------------------------------------------------------
    // 3. NPC SPRITES (Human Villagers)
    // ----------------------------------------------------------------
    // Elder Mira (Gray Hair, Purple Robe)
    const miraFrame = [
      ".....444444.....",
      "....44444444....",
      "....44ffff44....",
      "....44f00f44....",
      "....44ffff44....",
      ".....ffffff.....",
      "....UUUUUUUU....",
      "...UUUUUUUUUU...",
      "...UUUUUUUUUU...",
      "...UUUUUUUUUU...",
      "...UUUUUUUUUU...",
      "...UUUUUUUUUU...",
      "...UUUUUUUUUU...",
      "...UUUUUUUUUU...",
      "....00....00....",
      "....00....00....",
    ];
    pixelArtGenerator.createTexture(this, "npc_mira", miraFrame, 2);

    // Common NPC / Shopkeeper (Brown Hair, Green Shirt)
    const npcFrame = [
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "....HHffffHH....",
      "....Hff00ffH....",
      "....HffffffH....",
      ".....ffffff.....",
      "....GGGGGGGG....",
      "...GGGGGGGGGG...",
      "...GGGGGGGGGG...",
      "...GGGGGGGGGG...",
      "....KKKKKKKK....",
      "....KKKKKKKK....",
      "....KK....KK....",
      "....KK....KK....",
      "....00....00....",
      "....00....00....",
    ];
    pixelArtGenerator.createTexture(this, "npc", npcFrame, 2);

    // Trainer NPC (Red Cap, Red Vest)
    const trainerFrame = [
      ".....RRRRRR.....",
      "....RRRRRRRR....",
      "....RRffffRR....",
      "....Rf00ffRH....",
      "....RffffffH....",
      ".....ffffff.....",
      "....rrrrrrrr....",
      "...rrrrrrrrrr...",
      "...rrrr00rrrr...",
      "...rrrr00rrrr...",
      "....KKKKKKKK....",
      "....KKKKKKKK....",
      "....KK....KK....",
      "....KK....KK....",
      "....00....00....",
      "....00....00....",
    ];
    pixelArtGenerator.createTexture(this, "npc_trainer", trainerFrame, 2);

    const uiFrameGraphics = this.make.graphics({ x: 0, y: 0, add: false });
    uiFrameGraphics.fillStyle(0x000000, 0.9).fillRect(0, 0, 64, 64);
    uiFrameGraphics.lineStyle(2, 0xffffff, 1).strokeRect(0, 0, 64, 64);
    uiFrameGraphics.generateTexture("ui-frame", 64, 64);
  }
}
